# Generated by Django 5.0.2 on 2024-02-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_model_space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-do'), ('started', 'started'), ('in progress', 'in progress'), ('hold', 'hold'), ('completed', 'completed')], max_length=12),
        ),
    ]
